"""init 5 tables

Revision ID: 2defd64c5962
Revises: 
Create Date: 2026-08-28 09:31:14.049761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2defd64c5962'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('field_changes', sa.String(length=4000), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('params_summary', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('device_no', sa.String(length=64), nullable=False),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('station', sa.String(length=128), nullable=True),
    sa.Column('license', sa.String(length=32), nullable=True),
    sa.Column('sensitivity', sa.String(length=16), nullable=True),
    sa.Column('owner_contact', sa.String(length=64), nullable=True),
    sa.Column('is_synthetic', sa.Integer(), nullable=False),
    sa.Column('operating_condition', sa.String(length=256), nullable=True),
    sa.Column('weather', sa.String(length=128), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_no')
    )
    op.create_table('data_file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('batch_no', sa.String(length=64), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('device_no', sa.String(length=64), nullable=True),
    sa.Column('station', sa.String(length=128), nullable=True),
    sa.Column('license', sa.String(length=32), nullable=True),
    sa.Column('sensitivity', sa.String(length=16), nullable=True),
    sa.Column('is_synthetic', sa.Integer(), nullable=True),
    sa.Column('operating_condition', sa.String(length=256), nullable=True),
    sa.Column('weather', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.String(length=32), nullable=True),
    sa.Column('end_time', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=32), nullable=True),
    sa.Column('sample_period', sa.String(length=64), nullable=True),
    sa.Column('data_amount', sa.String(length=32), nullable=True),
    sa.Column('record_count', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('uploader_id', sa.String(length=36), nullable=True),
    sa.Column('upload_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key', name='ux_datafile_object_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_file')
    op.drop_table('batch')
    op.drop_table('user')
    op.drop_table('organization')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
